---
apiVersion: v1
kind: Namespace
metadata:
  name: pdfcomp
---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    name: pdfcomp
  name: pdfcomp
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
       spec:
          imagePullSecrets:
          - name: ocicontainerregauth 
          containers:
            - name: pdfcomp
              image: gru.ocir.io/grpm109q0sqx/pdfcomp:latest
              resources:
                limits:
                  memory: 500Mi
                requests:
                  memory: 5Mi
              imagePullPolicy: Always    
              volumeMounts:
                - name: nfs-share2
                  mountPath: /PDFs
          volumes:
          - name: nfs-share2
            nfs:
              server: 172.16.1.254
              path: /nfs/pdfcomp
          restartPolicy: OnFailure